# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [360, 230]
                    mode: outbound
        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [860, 530]
                    mode: outbound
        large:
            quality: 75
            filters:
                thumbnail:
                    size: [1060, 730]
                    mode: outbound