vich_uploader:
    db_driver: orm

    mappings:
        figure_image:
            uri_prefix: /images/figures
            upload_destination: '%kernel.project_dir%/public/images/figures'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        figure_main_image:
            uri_prefix: /images/figures/main_image
            upload_destination: '%kernel.project_dir%/public/images/figures/main_image'
            namer: Vich\UploaderBundle\Naming\UniqidNamer